"""
Django settings for IutParrainage project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# settings.py

# ... tout à la fin du fichier ...



"""
Django settings for IutParrainage project.
Optimisé pour le déploiement sur Render.com
"""
from datetime import timedelta
import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# Charge les variables locales (.env) si elles existent (pour le dev local)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =========================================================
# 🔐 SÉCURITÉ & CONFIGURATION DE BASE
# =========================================================

# SECRET_KEY : Doit être dans les variables d'environnement sur Render
SECRET_KEY = os.environ.get('SECRET_KEY', 'cle-de-secours-insecure-pour-dev-local')

# DEBUG : Doit être FALSE en production. 
# Sur Render, on ne met pas la variable DEBUG, donc ça passera à False par défaut.
DEBUG = os.environ.get('DEBUG') == 'True'

# ALLOWED_HOSTS : On accepte l'URL fournie par Render automatiquement
ALLOWED_HOSTS = []
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Pour le développement local ou les tests
if DEBUG:
    ALLOWED_HOSTS += ['localhost', '127.0.0.1', '*']


# =========================================================
# 📦 APPLICATIONS & MIDDLEWARE
# =========================================================

INSTALLED_APPS = [
    'jazzmin',                  # Interface Admin (doit être avant admin)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic', # Pour gérer les statiques en dev comme en prod
    'django.contrib.staticfiles',
    'axes',
    'import_export',
    'Parrainage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # ⚠️ INDISPENSABLE POUR RENDER
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # ✅ nouveau backend Django-Axes
    'django.contrib.auth.backends.ModelBackend',  # backend par défaut
]
# 🔒 Configuration sécurisée recommandée
AXES_ENABLED = True
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=10)
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']  # équivaut à "USER_OR_IP"
AXES_IPWARE_PROXY_COUNT = 0
AXES_OMLY_ADMIN_SITE = False
AXES_LOCKOUT_URL = '/verrouillage/'
AXES_RESET_ON_SUCCESS = True  # réinitialise les tentatives après un login réussi
# 🧰 Logs et alertes
AXES_NEVER_LOCKOUT_WHITELIST = ['127.0.0.1']
# pour debloquer l'admin faut utilser la commande python manage.py axes_reset
ROOT_URLCONF = 'IutParrainage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'IutParrainage.wsgi.application'


# =========================================================
# 🗄️ BASE DE DONNÉES (POSTGRESQL / NEON)
# =========================================================

DATABASES = {
    'default': dj_database_url.config(
        # Récupère l'URL depuis les variables d'environnement, sinon utilise sqlite en local
        default=os.environ.get("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=60,         # Évite de fermer/rouvrir la connexion trop souvent
        conn_health_checks=True, # Vérifie que la connexion est vivante (Anti-Erreur SSL)
        ssl_require=not DEBUG    # SSL obligatoire en production, facultatif en local
    )
}


# =========================================================
# 🛡️ VALIDATION MOT DE PASSE
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# =========================================================
# 🌍 INTERNATIONALISATION
# =========================================================

LANGUAGE_CODE = 'fr-fr' # On passe en Français
TIME_ZONE = 'Africa/Douala' # Ton fuseau horaire
USE_I18N = True
USE_TZ = True
# Imports en haut du fichier (ajoutez si manquant)
import os
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# ... TOUT VOTRE CODE EXISTANT ICI ...

# ================ AJOUTEZ CETTE PARTIE À LA FIN ================

# Configuration Sentry
if not DEBUG:  # Ne s'active que quand DEBUG=False (production)
    sentry_sdk.init(
        dsn="https://1c8051e00b42385db2ddc70122f244ac@o4510634551803904.ingest.de.sentry.io/4510662613074000",
        integrations=[DjangoIntegration()],
        
        # Performance monitoring (10% des requêtes)
        traces_sample_rate=0.1,
        
        # Profiling (optionnel)
        profiles_sample_rate=0.1,
        
        # Environnement
        environment="production",
        
        # Ajouter les infos utilisateur (comme vous l'avez)
        send_default_pii=True,
        
        # Désactiver en local
        debug=False,
    )
    
    print("✅ Sentry initialisé avec succès")
else:
    print("⚠️  Sentry désactivé (mode DEBUG activé)")

# =========================================================
# 🎨 FICHIERS STATIQUES (WHITENOISE)
# =========================================================

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Configuration WhiteNoise pour la compression et le cache
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =========================================================
# 📧 EMAIL (BREVO / SMTP)
# =========================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 2525
EMAIL_USE_TLS = True
# Récupérer ces infos depuis les variables d'environnement (plus sûr)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER') 
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')


# =========================================================
# 🔒 SÉCURITÉ PRODUCTION (S'active si DEBUG=False)
# =========================================================

if not DEBUG:
    # Force le HTTPS
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Sécurité des Cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    
    # Protection XSS et Content Type
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    
    # HSTS (Dit au navigateur de ne plus jamais utiliser HTTP simple)
    SECURE_HSTS_SECONDS = 31536000 # 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Important pour Render : Autoriser les requêtes venant du domaine HTTPS
    CSRF_TRUSTED_ORIGINS = [
        'https://' + (RENDER_EXTERNAL_HOSTNAME or 'iut-connect.onrender.com')
    ]

# Configuration Session
SESSION_COOKIE_AGE = 360000 # 1 heure


# =========================================================
# 🐛 SENTRY (LOGGING D'ERREURS)
# =========================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =========================================================
# 📝LOGGING
# =========================================================
# (Garde ton logging actuel, il est correct, je l'ai simplifié pour la lisibilité)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR', # On note seulement les erreurs graves
            'class': 'logging.FileHandler',
            'filename': 'erreurs.log', # Le fichier sera créé à la racine
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

JAZZMIN_SETTINGS = {
    "site_title": "IUT Parrainage — Admin",
    "site_header": "🎓 Billet de Parrainage",
    "site_brand": "BilletParrainage",
    "welcome_sign": "Bienvenue sur le panneau de gestion du parrainage IUT",
    "copyright": "Université de Ngaoundéré — IUT",
    "show_ui_builder": False,
    
    # --- COULEURS ---
    "theme": "cyborg",  # base dark
    "custom_css": "css/admin_custom.css",
    "custom_js": "js/admin_custom.js",

    # --- LOGO ---
    "site_logo": "images/logo-iut.jpeg",  # ajoute ce fichier dans static/images/

    # --- ICONES (optionnel) ---
    "icons": {
        "auth.user": "fas fa-user-shield",
        "auth.Group": "fas fa-users-cog",
        "Parrainage.EtudiantParrainage": "fas fa-id-card",
    },

    # --- MENU LATÉRAL ---
    "topmenu_links": [
        {"name": "Accueil", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "Parrainage.EtudiantParrainage"},
        {"name": "Support", "url": "mailto:support@iut-ndere.cm", "new_window": True},
    ],

    # --- THÈME ---
    "navigation_expanded": True,
}