# Generated by Django 5.2.9 on 2026-01-06 12:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('kind', models.CharField(choices=[('suggestion', 'Suggestion'), ('bug', 'Bug'), ('experience', 'Expérience utilisateur'), ('autre', 'Autre')], default='experience', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(max_length=60)),
                ('message', models.TextField(max_length=700)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avis Utilisateur',
                'verbose_name_plural': 'Avis Utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EtudiantNiveau1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('nom_prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit commencer par 6 et contenir exactement 9 chiffres.', regex='^6\\d{8}$')])),
                ('mention', models.CharField(max_length=40)),
                ('parcours', models.CharField(max_length=20)),
                ('niveau', models.CharField(default='N1', max_length=10)),
                ('annee_academique', models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], max_length=15)),
                ('code_secret', models.CharField(blank=True, max_length=128, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtudiantNiveau2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('nom_prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit commencer par 6 et contenir exactement 9 chiffres.', regex='^6\\d{8}$')])),
                ('mention', models.CharField(max_length=40)),
                ('parcours', models.CharField(max_length=20)),
                ('niveau', models.CharField(default='N2', max_length=10)),
                ('annee_academique', models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], max_length=15)),
                ('actif', models.BooleanField(default=True)),
                ('code_secret', models.CharField(blank=True, help_text='Code PIN à 4 chiffres', max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_emetteur', models.CharField(max_length=20)),
                ('niveau_emetteur', models.CharField(max_length=5)),
                ('type_probleme', models.CharField(choices=[('absent', 'Parrain/Filleul injoignable'), ('inapte', "Incompatibilité d'humeur"), ('harcelement', 'Harcèlement / Comportement déplacé'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Parrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('filleul', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parrainage', to='Parrainage.etudiantniveau1')),
                ('parrain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to='Parrainage.etudiantniveau2')),
            ],
        ),
    ]
