# Generated by Django 5.2.9 on 2025-12-29 19:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantNiveau1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nom_prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telephone', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit commencer par 6 et contenir exactement 9 chiffres.', regex='^6\\d{8}$')])),
                ('mention', models.CharField(choices=[('GI', 'Génie Informatique'), ('GM', 'Génie Mécanique'), ('GE', 'Génie Électrique')], max_length=10)),
                ('parcours', models.CharField(choices=[('RT', 'Réseaux et Télécommunications'), ('GLO', 'Génie Logiciel'), ('IA', 'Intelligence Artificielle'), ('AUTRE', 'Autre')], max_length=20)),
                ('niveau', models.CharField(default='N1', max_length=10)),
                ('annee_academique', models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], max_length=15)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtudiantNiveau2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nom_prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telephone', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit commencer par 6 et contenir exactement 9 chiffres.', regex='^6\\d{8}$')])),
                ('mention', models.CharField(choices=[('GI', 'Génie Informatique'), ('GM', 'Génie Mécanique'), ('GE', 'Génie Électrique')], max_length=10)),
                ('parcours', models.CharField(choices=[('RT', 'Réseaux et Télécommunications'), ('GLO', 'Génie Logiciel'), ('IA', 'Intelligence Artificielle'), ('AUTRE', 'Autre')], max_length=20)),
                ('niveau', models.CharField(default='N2', max_length=10)),
                ('annee_academique', models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], max_length=15)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('filleul', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parrainage', to='Parrainage.etudiantniveau1')),
                ('parrain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to='Parrainage.etudiantniveau2')),
            ],
        ),
    ]
