# Generated by Django 5.2.9 on 2026-01-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parrainage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantniveau1',
            name='matricule',
            field=models.CharField(max_length=51),
        ),
    ]
