# Generated by Django 5.2.9 on 2025-12-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parrainage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantniveau1',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etudiantniveau2',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
