# Generated by Django 5.2.9 on 2026-01-11 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parrainage', '0002_alter_etudiantniveau1_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantniveau1',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit commencer par 6 et contenir exactement 9 chiffres.', regex='^6\\d{8}$')]),
        ),
    ]
