# Generated by Django 5.2.9 on 2025-12-30 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parrainage', '0002_alter_etudiantniveau1_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantniveau1',
            name='telephone',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit commencer par 6 et contenir exactement 9 chiffres.', regex='^6\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='etudiantniveau2',
            name='telephone',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit commencer par 6 et contenir exactement 9 chiffres.', regex='^6\\d{8}$')]),
        ),
    ]
