# Generated by Django 5.2.9 on 2025-12-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parrainage', '0003_alter_etudiantniveau1_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantniveau2',
            name='matricule',
            field=models.CharField(max_length=50),
        ),
    ]
