# Generated by Django 5.2.9 on 2026-01-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parrainage', '0003_alter_etudiantniveau1_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantniveau2',
            name='code_secret',
            field=models.CharField(blank=True, help_text='Code PIN à 4 chiffres', max_length=10, null=True),
        ),
    ]
