# Generated by Django 5.2.9 on 2025-12-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parrainage', '0004_alter_etudiantniveau2_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantniveau1',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
