# Generated by Django 5.2.9 on 2026-02-13 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parrainage', '0005_alter_etudiantniveau2_code_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantniveau2',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit commencer par 6 et contenir exactement 9 chiffres.', regex='^6\\d{8}$')]),
        ),
    ]
