# Generated by Django 5.2.9 on 2025-12-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parrainage', '0005_alter_etudiantniveau1_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantniveau2',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
