# Generated by Django 5.2.9 on 2025-12-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parrainage', '0006_alter_etudiantniveau2_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantniveau2',
            name='mention',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='etudiantniveau2',
            name='parcours',
            field=models.CharField(max_length=20),
        ),
    ]
