# Generated by Django 5.2.9 on 2025-12-30 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parrainage', '0007_alter_etudiantniveau2_mention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantniveau1',
            name='matricule',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='etudiantniveau1',
            name='mention',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='etudiantniveau1',
            name='parcours',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='etudiantniveau1',
            name='telephone',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit commencer par 6 et contenir exactement 9 chiffres.', regex='^6\\d{8}$')]),
        ),
    ]
