# Generated by Django 5.2.9 on 2025-12-30 17:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parrainage', '0008_alter_etudiantniveau1_matricule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('filleuls', models.ManyToManyField(blank=True, related_name='chat_groups', to='Parrainage.etudiantniveau1')),
                ('parrain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_group', to='Parrainage.etudiantniveau2')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur_nom', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('horodatage', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Parrainage.chatgroup')),
            ],
            options={
                'ordering': ['horodatage'],
            },
        ),
    ]
