# Generated by Django 5.2.9 on 2025-12-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parrainage', '0010_message_fichier_message_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
        migrations.DeleteModel(
            name='ChatGroup',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
