# Generated by Django 5.2.9 on 2025-12-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parrainage', '0011_remove_message_group_delete_chatgroup_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantniveau2',
            name='code_secret',
            field=models.CharField(blank=True, help_text='Code PIN à 4 chiffres', max_length=4, null=True),
        ),
    ]
