# Generated by Django 5.2.9 on 2025-12-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parrainage', '0012_etudiantniveau2_code_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('kind', models.CharField(choices=[('suggestion', 'Suggestion'), ('bug', 'Bug'), ('experience', 'Expérience utilisateur'), ('autre', 'Autre')], default='experience', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(max_length=60)),
                ('message', models.TextField(max_length=700)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avis Utilisateur',
                'verbose_name_plural': 'Avis Utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
