# Generated by Django 5.2.9 on 2026-01-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parrainage', '0013_avis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_emetteur', models.CharField(max_length=20)),
                ('niveau_emetteur', models.CharField(max_length=5)),
                ('type_probleme', models.CharField(choices=[('absent', 'Parrain/Filleul injoignable'), ('inapte', "Incompatibilité d'humeur"), ('harcelement', 'Harcèlement / Comportement déplacé'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='etudiantniveau1',
            name='code_secret',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
